CREATE TABLE company(
    ID INT,
    COMPANY_NAME VARCHAR(255)
);

CREATE TABLE employee (
    ID INT,
    NAME VARCHAR(255),
    AGE INT,
    GENDER VARCHAR(10),
    SALARY DOUBLE,
    COMPANY_ID VARCHAR(255)
);

CREATE TABLE parking_boy(
    ID INT,
    NICKNAME VARCHAR(255),
    EMPLOYEE_ID INT
);